title: Suhrid Krishna Chatterjee
description: Data & Business Analyst
site_title: '@skctcdgit - Suhrid Krishna Chatterjee'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: skctcdgit
# blog_url: https://www.nagekar.com
email: c.suhrid@gmail.com
# keybase_username: abhn
# twitter_username: abhn_
# reddit_username: abhn

# absolute or relative
profile_picture: assets/images/skcpp.jpg

# Google Analytics ID
google_analytics: 
