title: Suhrid Krishna Chatterjee
description: Data & Business Analytics Professional
site_title: '@skctcdgit - Suhrid Krishna Chatterjee'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: skctcdgit
email: c.suhrid@gmail.com

# absolute or relative
profile_picture: assets/images/skc photo.png

# Google Analytics ID
google_analytics: 
